version: '3.1'
services:
    nginx:
        #build:
            #context: ./
            #dockerfile: nginx/Dockerfile
        image: nginx:latest
        #image: tiangolo/uwsgi-nginx:python3.9
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            #- ./nginx/get-data.py
        networks:
            - my-network
        ports:
            - 80:80
        depends_on:
            - flask
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        image: flask:latest
        container_name: flask
        volumes:
            - ./:/devops-exercise-docker-flask/
        environment:
          FLASK_APP: app.py
          APP_LINE: "Hello, World!"
          PORT: 5000
          ENVIRONMENT: dev
        command: python3 -m flask run --host=0.0.0.0 --port 5000
        networks:
            my-network:
                aliases:
                    - flask-app
        ports:
            - 8080:5000
networks:
    my-network:
