version: '3.1'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - my-network
        ports:
            - 80:80
        depends_on:
            - flask
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        image: flask:latest
        container_name: flask
        volumes:
            - ./:/devops-exercise-docker-flask/
        environment:
          FLASK_APP: app.py
          PATH: ~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
          PORT: 5000
          ENVIRONMENT: dev
        command: python3 -m flask run --host=0.0.0.0
        networks:
            my-network:
                aliases:
                    - flask-app
        ports:
            - 8080:5000
networks:
    my-network:

